# nginx/Dockerfile

# Começa com a imagem oficial e leve do NGINX.
FROM nginx:1.21.3-alpine

# Remove a configuração padrão do NGINX para garantir que a nossa seja usada.
RUN rm /etc/nginx/conf.d/default.conf

# Copia o nosso arquivo de configuração personalizado (que criamos acima)
# para dentro do container, no local onde o NGINX procura por configurações.
COPY default.conf /etc/nginx/conf.d/